"""Dossier reporting: Markdown / printable-HTML reports and IP geolocation.

Reports are rendered from a case's persisted graph with zero third-party
dependencies. Geolocation reuses :class:`IPService` (ip-api.com) and is shared
by both the report tables and the interactive map endpoint.
"""

from __future__ import annotations

import html
from datetime import datetime, timezone

from app.core.concurrency import gather_bounded
from app.schemas.cases import Case, GeoPoint
from app.schemas.common import SourceStatus
from app.schemas.graph import Edge, Entity
from app.schemas.ip import IPQuery

_TYPE_ORDER = [
    "person", "email", "username", "phone", "domain", "ip",
    "account", "url", "organization", "asn", "address", "breach", "note",
]


def _value(node_id: str) -> str:
    _, _, rest = node_id.partition(":")
    return rest or node_id


def _grouped(entities: list[Entity]) -> dict[str, list[Entity]]:
    groups: dict[str, list[Entity]] = {}
    for e in entities:
        groups.setdefault(e.type.value, []).append(e)
    ordered = {t: groups[t] for t in _TYPE_ORDER if t in groups}
    for t, items in groups.items():  # any types not in the canonical order
        ordered.setdefault(t, items)
    for items in ordered.values():
        items.sort(key=lambda e: (-e.confidence, e.value))
    return ordered


async def collect_geo(ip_service, ips: list[str]) -> list[GeoPoint]:
    """Geolocate a list of IPs concurrently (best effort)."""

    async def _one(ip: str) -> GeoPoint:
        try:
            result = await ip_service.investigate(IPQuery(ip=ip))
        except Exception:  # noqa: BLE001 — geo is best-effort
            return GeoPoint(ip=ip)
        for r in result.results:
            if r.source == "ip-api.com" and r.status == SourceStatus.found:
                d = r.data
                return GeoPoint(
                    ip=ip, lat=d.get("lat"), lon=d.get("lon"),
                    country=d.get("country"), city=d.get("city"),
                    org=d.get("org") or d.get("isp"), asn=d.get("as"),
                )
        return GeoPoint(ip=ip)

    outcomes = await gather_bounded([(lambda ip=ip: _one(ip)) for ip in ips])
    return [o for o in outcomes if isinstance(o, GeoPoint)]


# --------------------------------------------------------------------- Markdown

def build_markdown(case: Case, entities: list[Entity], edges: list[Edge], geo: list[GeoPoint]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    groups = _grouped(entities)
    lines: list[str] = [
        f"# OSINT Dossier — {case.name}",
        "",
        "`UNCLASSIFIED // OSINT // FOR AUTHORIZED USE ONLY`",
        "",
        f"_Generated {now} · OSINTp_",
        "",
        "## Summary",
        "",
        f"- **Entities:** {len(entities)}",
        f"- **Relationships:** {len(edges)}",
        "- **By type:** " + ", ".join(f"{t} ({len(v)})" for t, v in groups.items()),
        f"- **Created:** {case.created_at}",
        f"- **Updated:** {case.updated_at}",
    ]
    if case.notes:
        lines += ["", "## Case Notes", "", case.notes]

    lines += ["", "## Entities", ""]
    for t, items in groups.items():
        lines.append(f"### {t} ({len(items)})")
        lines.append("")
        lines.append("| Value | Confidence | Origin | Discovered by |")
        lines.append("|---|---|---|---|")
        for e in items:
            lines.append(
                f"| {e.value} | {e.confidence:.2f} | {e.origin} | {e.discovered_by or '—'} |"
            )
        lines.append("")

    if edges:
        lines += ["## Relationships", "", "| Source | Relation | Target | Confidence | Origin |",
                  "|---|---|---|---|---|"]
        for ed in edges:
            lines.append(
                f"| {_value(ed.source)} | {ed.relation} | {_value(ed.target)} | "
                f"{ed.confidence:.2f} | {ed.origin} |"
            )
        lines.append("")

    located = [g for g in geo if g.lat is not None]
    if geo:
        lines += ["## Geolocation", "", "| IP | Country | City | Org | Lat | Lon |",
                  "|---|---|---|---|---|---|"]
        for g in geo:
            lines.append(
                f"| {g.ip} | {g.country or '—'} | {g.city or '—'} | {g.org or '—'} | "
                f"{g.lat if g.lat is not None else '—'} | {g.lon if g.lon is not None else '—'} |"
            )
        lines.append("")
        if not located:
            lines.append("> No coordinates resolved (geolocation source unreachable).")
            lines.append("")

    lines.append("---")
    lines.append("_Generated by OSINTp. Public-source intelligence — use lawfully and ethically._")
    return "\n".join(lines)


# ------------------------------------------------------------------------- HTML

def _h(value) -> str:
    return html.escape(str(value), quote=True)


def build_html(case: Case, entities: list[Entity], edges: list[Edge], geo: list[GeoPoint]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    groups = _grouped(entities)

    chips = "".join(
        f'<span class="chip">{_h(t)} <b>{len(v)}</b></span>' for t, v in groups.items()
    )

    ent_sections = []
    for t, items in groups.items():
        rows = "".join(
            f"<tr><td>{_h(e.value)}</td><td>{e.confidence:.2f}</td>"
            f'<td><span class="org-{_h(e.origin)}">{_h(e.origin)}</span></td>'
            f"<td>{_h(e.discovered_by or '—')}</td></tr>"
            for e in items
        )
        ent_sections.append(
            f"<h3>{_h(t)} <span class='n'>{len(items)}</span></h3>"
            "<table><thead><tr><th>Value</th><th>Conf.</th><th>Origin</th>"
            f"<th>Discovered by</th></tr></thead><tbody>{rows}</tbody></table>"
        )

    edge_rows = "".join(
        f"<tr><td>{_h(_value(ed.source))}</td><td><em>{_h(ed.relation)}</em></td>"
        f"<td>{_h(_value(ed.target))}</td><td>{ed.confidence:.2f}</td>"
        f"<td>{_h(ed.origin)}</td></tr>"
        for ed in edges
    )
    edge_section = (
        "<h2>Relationships</h2><table><thead><tr><th>Source</th><th>Relation</th>"
        "<th>Target</th><th>Conf.</th><th>Origin</th></tr></thead>"
        f"<tbody>{edge_rows}</tbody></table>"
        if edges else ""
    )

    geo_section = ""
    if geo:
        geo_rows = "".join(
            f"<tr><td>{_h(g.ip)}</td><td>{_h(g.country or '—')}</td>"
            f"<td>{_h(g.city or '—')}</td><td>{_h(g.org or '—')}</td>"
            f"<td>{g.lat if g.lat is not None else '—'}</td>"
            f"<td>{g.lon if g.lon is not None else '—'}</td></tr>"
            for g in geo
        )
        geo_section = (
            "<h2>Geolocation</h2><table><thead><tr><th>IP</th><th>Country</th>"
            "<th>City</th><th>Org</th><th>Lat</th><th>Lon</th></tr></thead>"
            f"<tbody>{geo_rows}</tbody></table>"
        )

    notes = f"<h2>Case Notes</h2><p>{_h(case.notes)}</p>" if case.notes else ""

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>OSINT Dossier — {_h(case.name)}</title>
<style>
  :root {{ --ink:#16202a; --muted:#5b6b78; --line:#d8e0e6; --accent:#0d7a52; }}
  * {{ box-sizing: border-box; }}
  body {{ font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    color: var(--ink); margin: 0; background: #eef2f4; }}
  .sheet {{ max-width: 880px; margin: 24px auto; background: #fff; padding: 40px 48px;
    box-shadow: 0 1px 6px rgba(0,0,0,.12); }}
  .banner {{ background: repeating-linear-gradient(45deg,#0d7a52 0 14px,#0a6344 14px 28px);
    color: #fff; text-align: center; letter-spacing: 3px; font-size: 11px; font-weight: 700;
    padding: 4px; border-radius: 3px; }}
  h1 {{ margin: 14px 0 2px; font-size: 26px; }}
  h2 {{ margin: 28px 0 8px; padding-bottom: 4px; border-bottom: 2px solid var(--accent); font-size: 18px; }}
  h3 {{ margin: 16px 0 6px; font-size: 14px; text-transform: capitalize; color: var(--accent); }}
  h3 .n {{ background: var(--accent); color: #fff; border-radius: 10px; padding: 0 7px; font-size: 11px; }}
  .meta {{ color: var(--muted); font-size: 13px; }}
  .chips {{ margin: 12px 0; }}
  .chip {{ display: inline-block; border: 1px solid var(--line); border-radius: 12px;
    padding: 2px 10px; margin: 3px 4px 3px 0; font-size: 12px; }}
  table {{ width: 100%; border-collapse: collapse; margin: 6px 0 14px; font-size: 13px; }}
  th, td {{ text-align: left; padding: 6px 8px; border-bottom: 1px solid var(--line); }}
  th {{ color: var(--muted); font-weight: 600; font-size: 11px; text-transform: uppercase; letter-spacing: .5px; }}
  td {{ word-break: break-word; }}
  .org-manual {{ color: var(--accent); font-weight: 700; }}
  .toolbar {{ text-align: center; margin: 16px; }}
  button {{ font: inherit; background: var(--accent); color: #fff; border: 0; border-radius: 4px;
    padding: 9px 18px; cursor: pointer; }}
  footer {{ color: var(--muted); font-size: 12px; margin-top: 24px; border-top: 1px solid var(--line); padding-top: 10px; }}
  @media print {{ body {{ background: #fff; }} .sheet {{ box-shadow: none; margin: 0; }} .toolbar {{ display: none; }} }}
</style></head>
<body>
  <div class="toolbar"><button onclick="window.print()">🖨 Print / Save as PDF</button></div>
  <div class="sheet">
    <div class="banner">UNCLASSIFIED // OSINT // FOR AUTHORIZED USE ONLY</div>
    <h1>OSINT Dossier — {_h(case.name)}</h1>
    <div class="meta">Generated {now} · OSINTp · case <code>{_h(case.id)}</code></div>
    <div class="chips">{chips}</div>
    <p class="meta"><b>{len(entities)}</b> entities · <b>{len(edges)}</b> relationships ·
       created {_h(case.created_at)} · updated {_h(case.updated_at)}</p>
    {notes}
    <h2>Entities</h2>
    {''.join(ent_sections)}
    {edge_section}
    {geo_section}
    <footer>Generated by OSINTp. Public-source intelligence — use lawfully and ethically.</footer>
  </div>
</body></html>"""
